### ISSUE TITLE
Issues on container up. Host Ubuntu 22.04, all images

### ISSUE THREAD

**Issue by takaite** [eniocarboni/docker-ubuntu-systemd#1]
Hello. I used to use a image of mine on Ubuntu 18.04 that works  successfully with systemd. After upgrade to 22.04 it stopped to work and searching for a solution I came to your project.
But I had no success using your images: 

- 18.04 is getting the same issue of mine, 
- 20.04 stucks on run and 
- 22.04 dies after run.

Running interactive, I got this error message:
```
docker run -it --privileged --volume=/sys/fs/cgroup:/sys/fs/cgroup:rw eniocarboni/docker-ubuntu-systemd:latest
systemd 249.11-0ubuntu3 running in system mode (+PAM +AUDIT +SELINUX +APPARMOR +IMA +SMACK +SECCOMP +GCRYPT +GNUTLS -OPENSSL +ACL +BLKID +CURL +ELFUTILS -FIDO2 +IDN2 -IDN +IPTC +KMOD +LIBCRYPTSETUP -LIBFDISK +PCRE2 -PWQUALITY -P11KIT -QRENCODE +BZIP2 +LZ4 +XZ +ZLIB +ZSTD -XKBCOMMON +UTMP +SYSVINIT default-hierarchy=unified)
Detected virtualization docker.
Detected architecture x86-64.

Welcome to Ubuntu 22.04 LTS!

Failed to create /init.scope control group: No such file or directory
Failed to allocate manager object: No such file or directory
[!!!!!!] Failed to allocate manager object.
Exiting PID 1...
```
Could you give me any clue?

A note: On command before I tried to change volume from "ro"  to "rw", but got the same issue.

Best Regards

**Comment by eniocarboni** [comment]
I @takaite,
until the problem is resolved between systemd, docker and the various distributions you could try to use:

`--volume=/sys/fs/cgroup:/sys/fs/cgroup:rw --cgroupns=host`

I hope it can help you

**Comment by takaite** [comment]
> --volume=/sys/fs/cgroup:/sys/fs/cgroup:rw --cgroupns=host

It works successfully. Both on yours as mine.

I didn't studied what means the new parameter and will read about it later.

Tks
