### ISSUE TITLE
/sys/fs/cgroup:/sys/fs/cgroup:ro  or   ..cgroup:rw

### ISSUE THREAD

**Issue by hellower** [eniocarboni/docker-ubuntu-systemd#2]
1. error   (--volume=/sys/fs/cgroup:/sys/fs/cgroup:ro )
[root@tnt-factory-ubuntu:/root]
__STAGE__# docker run --detach --privileged --volume=/sys/fs/cgroup:/sys/fs/cgroup:ro eniocarboni/docker-ubuntu-systemd:latest
feb850f25289f67fd2893bd4bb77d1d2078fba6e4cd820afef26f22b6fa3c15d
[root@tnt-factory-ubuntu:/root]
__STAGE__# docker ps -a
CONTAINER ID   IMAGE                                      COMMAND                  CREATED         STATUS                      PORTS     NAMES
feb850f25289   eniocarboni/docker-ubuntu-systemd:latest   "/lib/systemd/systemd"   2 seconds ago   Exited (255) 1 second ago             suspicious_hawking
[root@tnt-factory-ubuntu:/root]   

2. good (--volume=/sys/fs/cgroup:/sys/fs/cgroup:rw) 
__STAGE__# docker run --detach --privileged --volume=/sys/fs/cgroup:/sys/fs/cgroup:rw eniocarboni/docker-ubuntu-systemd:latest
9faab534415c47318071a1e39456e531ae2749c123805fb781a6e00ba7206143
[root@tnt-factory-ubuntu:/root]
__STAGE__# docker ps -a
CONTAINER ID   IMAGE                                      COMMAND                  CREATED          STATUS                       PORTS     NAMES
9faab534415c   eniocarboni/docker-ubuntu-systemd:latest   "/lib/systemd/systemd"   2 seconds ago    Up 2 seconds                           eloquent_yonath
..
[root@tnt-factory-ubuntu:/root]

Which option is right ?

**Comment by eniocarboni** [comment]
I @hellower ,
In previous Linux distributions (e.g. Ubuntu 20.04 LTS or lower) the first solution was fine.
Now I can't say, however see also issue #1.

See also on [serverfault](https://serverfault.com/questions/1053187/systemd-fails-to-run-in-a-docker-container-when-using-cgroupv2-cgroupns-priva/1054414#1054414) or try "Docker Systemd cgroup v2" in search engines.

**Comment by Bilge** [comment]
Can confirm changing `ro` to `rw` was the only way to get this working in WSL2. It is the default, so just omitting the modifier is also fine.
