### ISSUE TITLE
End of the road at 11 dockers

### ISSUE THREAD

**Issue by egzakutacno** [eniocarboni/docker-ubuntu-systemd#3]
Hello Mr. Enio. First of all, thank you so much for your time to develop this specific image. It's a lifesaver for someone like me, my skills are non existent. 
I have used this on 4gb ram VPS and I hit a wall at 10 Dockers, and I figure it has to be something with my resources, even dough htop is displaying all system go, and everything is under 30% of use.
I rented 16gb 6cpu vps, and again I hit that wall at 11 dockers this time. 

Could you please point me in the right direction to solve this.

And there is no way around it, I need this image with systemd , I can't try and find another image.

**Comment by eniocarboni** [comment]
Hi @egzakutacno,
 
can you send the docker logs of the last instance (the 10th or 11th) that you can't start.

What's your OS and are you use docker or other graphics tools?
I can start more instance like in this screenshot:
![Screenshot_20231226_161227](https://github.com/eniocarboni/docker-ubuntu-systemd/assets/7113911/a48aee49-540d-415b-a48a-d198ec3c8d91)

**Comment by egzakutacno** [comment]
dear mr. Enio. here is screenshot. and i cant see any errors. on portainer those dockers are just "exited" with error 225, or 255 im not sure. 
![failed](https://github.com/eniocarboni/docker-ubuntu-systemd/assets/4127261/376d918c-d30a-4020-9da1-72a101865f27)

would you please, email me at chakyagm@gmail.com , i am willing to give you access to my vps, and you can see for yourself. as i am nothing more than a skript kiddie.

**Comment by egzakutacno** [comment]
`CONTAINER ID   IMAGE                                      COMMAND                  CREATED          STATUS          PORTS     NAMES
ef56d82a2a2f   eniocarboni/docker-ubuntu-systemd:latest   "/lib/systemd/systemd"   11 seconds ago   Up 10 seconds             nostalgic_elgamal
ad74419c195f   eniocarboni/docker-ubuntu-systemd:latest   "/lib/systemd/systemd"   11 seconds ago   Up 10 seconds             naughty_lamarr
76d029c42d34   eniocarboni/docker-ubuntu-systemd:latest   "/lib/systemd/systemd"   11 seconds ago   Up 11 seconds             agitated_antonelli
2eedd1ed0b25   eniocarboni/docker-ubuntu-systemd:latest   "/lib/systemd/systemd"   12 seconds ago   Up 11 seconds             tender_brattain
520069d3ceb0   eniocarboni/docker-ubuntu-systemd:latest   "/lib/systemd/systemd"   12 seconds ago   Up 11 seconds             awesome_heyrovsky
8dae05fd1239   eniocarboni/docker-ubuntu-systemd:latest   "/lib/systemd/systemd"   12 seconds ago   Up 12 seconds             recursing_rhodes
8b84aad54aa4   eniocarboni/docker-ubuntu-systemd:latest   "/lib/systemd/systemd"   13 seconds ago   Up 12 seconds             nervous_lalande
9fe370f404e6   eniocarboni/docker-ubuntu-systemd:latest   "/lib/systemd/systemd"   13 seconds ago   Up 12 seconds             sweet_aryabhata
e39d11ae9f46   eniocarboni/docker-ubuntu-systemd:latest   "/lib/systemd/systemd"   14 seconds ago   Up 13 seconds             trusting_elbakyan
5368f341322e   eniocarboni/docker-ubuntu-systemd:latest   "/lib/systemd/systemd"   14 seconds ago   Up 13 seconds             cranky_dirac
4626a8493d82   eniocarboni/docker-ubuntu-systemd:latest   "/lib/systemd/systemd"   14 seconds ago   Up 14 seconds             confident_dirac
20d990e8e8ff   eniocarboni/docker-ubuntu-systemd:latest   "/lib/systemd/systemd"   15 seconds ago   Up 14 seconds             nifty_sinoussi
root@vmi1573465:~# for i in {1..20}; do     docker run --detach --privileged --volume=/sys/fs/cgroup:/sys/fs/cgroup:ro eniocarboni/docker-ubuntu-systemd:latest; done
8ed29b61378d7dfed302e4c6c322a49767788c0031d685007940e5570fca2ed4
ffb5657099733c69247a118b363d5de82bc5fed1a7196a6a72532b6d32725a00
cb821928b98f727a5e0d071fa111160aeca4c6e6982fc8c6cd47df5577e0a57a
fe3eba1428097f1a058af74b169ce95c8bbb34b1971ba57ab8360c8c6d7c1e35
7c86f054ca15a10f3b32ac8b9ad31b71dff41c13fe826c328772ac73fcf3cd80
b74792ec65d4dadc02af8608ba5427a5669feccd38443673ee5e833a01f70aeb
ecc0f9fd324b0627b944e586b35aee738358e6f27b9cd66404c497978b1d5c9e
6ebba9f487c2ac5e114d2f72c2dc4bef34ed1b94e9080c2ab5ac82b620fd966b
139a4b954c5016ad716116d2a1d6c32a84f92d89cbc7aec79171235072b5d59b
0a05b0924955e713c0ec2f859c278fc0be43da815640ddc8548f3da87d6906de
71dfbe1f8001270113f562370a391e34af3b6507645a523cc0c7512008069155
b1fc0fedce657a7d3fe4b05de9c4a4adedb12852f80302f89f9516baeece6493
3ef07094a5b974efb386942111f3a817b3f3d3f38322470d7f724101318c21ed
f1bee1c70a71b6c2adff07176a7eea72768ab5a50f2795ea117bacafdc4dd27e
c72c314ebaf722dd751e22bf2dcf0fd70754fd1131ca917498f6bc1458f9592e
bcdcbb0930bfe28e9845599b41110cf497f3d2eeb35ca3c2bda3fce26fb2cb00
291233dde101f2792d77bfe13a2635fac127b48fcf61dfc7f8c3b7f6110da935
93df3ff157a00929e5f2188a1259ac9cde086e731d3ea1e8332124fd9eea89a8
a36acd1bfead29da33ff65555b04922b29911cf894d37883e1b36daee2d7a0b8
68f8988e97210e12495ca1dbe91de58cf4a938c188ab8408e9f1bd4f0beb177b
root@vmi1573465:~# docker ps
CONTAINER ID   IMAGE                                      COMMAND                  CREATED          STATUS          PORTS     NAMES
ef56d82a2a2f   eniocarboni/docker-ubuntu-systemd:latest   "/lib/systemd/systemd"   43 seconds ago   Up 42 seconds             nostalgic_elgamal
ad74419c195f   eniocarboni/docker-ubuntu-systemd:latest   "/lib/systemd/systemd"   43 seconds ago   Up 42 seconds             naughty_lamarr
76d029c42d34   eniocarboni/docker-ubuntu-systemd:latest   "/lib/systemd/systemd"   43 seconds ago   Up 42 seconds             agitated_antonelli
2eedd1ed0b25   eniocarboni/docker-ubuntu-systemd:latest   "/lib/systemd/systemd"   44 seconds ago   Up 43 seconds             tender_brattain
520069d3ceb0   eniocarboni/docker-ubuntu-systemd:latest   "/lib/systemd/systemd"   44 seconds ago   Up 43 seconds             awesome_heyrovsky
8dae05fd1239   eniocarboni/docker-ubuntu-systemd:latest   "/lib/systemd/systemd"   44 seconds ago   Up 43 seconds             recursing_rhodes
8b84aad54aa4   eniocarboni/docker-ubuntu-systemd:latest   "/lib/systemd/systemd"   45 seconds ago   Up 44 seconds             nervous_lalande
9fe370f404e6   eniocarboni/docker-ubuntu-systemd:latest   "/lib/systemd/systemd"   45 seconds ago   Up 44 seconds             sweet_aryabhata
e39d11ae9f46   eniocarboni/docker-ubuntu-systemd:latest   "/lib/systemd/systemd"   46 seconds ago   Up 45 seconds             trusting_elbakyan
5368f341322e   eniocarboni/docker-ubuntu-systemd:latest   "/lib/systemd/systemd"   46 seconds ago   Up 45 seconds             cranky_dirac
4626a8493d82   eniocarboni/docker-ubuntu-systemd:latest   "/lib/systemd/systemd"   46 seconds ago   Up 45 seconds             confident_dirac
20d990e8e8ff   eniocarboni/docker-ubuntu-systemd:latest   "/lib/systemd/systemd"   47 seconds ago   Up 46 seconds             nifty_sinoussi
root@vmi1573465:~# `

**Comment by egzakutacno** [comment]
![Uploading fail 2.png…]()

**Comment by egzakutacno** [comment]
dear @eniocarboni 
i am using ubuntu 20.04 on vps, just with CLI no graphical interface. i think i have VNC access if needed. 
![fail 2](https://github.com/eniocarboni/docker-ubuntu-systemd/assets/4127261/e8c2cd7c-fc8f-4414-a3b6-6d968fdf6464)

**Comment by egzakutacno** [comment]
first i was having issues creating more than 10, lets say it was my mistake, for some reason if i use you :latest build then i cant create more, but if i use .focal then i can. 

but issue persist in a different way.

i managed to create 20 with .focal and i start installing software on it (the whole reason for having these containers)
but as i try to install software on 13th docker i get an error, not always the same error, sometimes it dbus error, sometimes "Enabling service
Failed to connect to bus: No such file or directory"

the software in question is a simple script that talks to API on the other side:
sudo wget https://downloads-builds.myria.com/node/install.sh -O - | sudo bash

and one more thing, as i was downloading it on 10th and 11th i got this warning:
"Failed to allocate directory watch: Too many open files"

**Comment by egzakutacno** [comment]
this is the output when installed on host machine:
Enabling service
Created symlink /etc/systemd/system/multi-user.target.wants/myria-node.service → /etc/systemd/system/myria-node.service.

i am sure that is where the problem lies with containers and the way they use systemd

**Comment by egzakutacno** [comment]
the easiest way to reproduce the problem is just trying to install this software on your dockers enough times. 
that way you will understand the problem more clearly than i can explain it. i know how i sound to a professional like you, whit my uncoherent writing and formatting. i've sent you a tip as a thanks for everything that you did already :)
thank you so much.

**Comment by eniocarboni** [comment]
Hi @egzakutacno,
the main problem seems to me "**Failed to allocate directory watch: Too many open files**".

On your host server (Ubuntu 20.04) what is the result of the command:
`sysctl fs.inotify`

You should try increasing these values and then try again with containers (for example for the fs.inotify.max_user_instances parameter):

`sudo sysctl -w fs.inotify.max_user_instances=2048`

In general, however, I would say that it is a problem on the limit of some resources (open files, CPU, RAM)
You should check the docker log for containers that are killed with the command:

`docker logs <container id>`

**Comment by egzakutacno** [comment]
hi, thanks for getting back to me. i spent the whole day today to try and figure that out. i saw that as a probable cause.

`root@vmi1528786:~# sysctl fs.inotify
fs.inotify.max_queued_events = 16384
fs.inotify.max_user_instances = 128
fs.inotify.max_user_watches = 65536
root@vmi1528786:~# sudo sysctl -w fs.inotify.max_user_instances=2048
fs.inotify.max_user_instances = 2048`

i will let you know how it goes.

**Comment by egzakutacno** [comment]
dear Enio, you were right. problem was resolved when i used this command: `sudo sysctl -w fs.inotify.max_user_instances=2048`

would you feel comfortable sharing your work email, so i can expand on the next problem that i'm encountering. but i have to share some of my personal details in my explanation. your work has helped me a lot, and i am probably using it the way it was not intended, but its the only way to achieve what i need.
