### ISSUE TITLE
gpg invalid keyring

### ISSUE THREAD

**Issue by janArb** [eniocarboni/docker-ubuntu-systemd#4]
Hi,
I use your docker container latest and cannot import gpg keys. Any idea how this could be connected to systemd integration? In normal Ubuntu VM this is working:

```
sudo /usr/bin/apt-key adv --no-tty --keyserver hkp://keyserver.ubuntu.com:80 --recv B1998361219BD9C9
Executing: /tmp/apt-key-gpghome.TZfrFmVS9y/gpg.1.sh --no-tty --keyserver hkp://keyserver.ubuntu.com:80 --recv B1998361219BD9C9
gpg: CRC error; 00C451 - 687B25
gpg: read_block: read error: Invalid keyring
gpg: Total number processed: 0
```

I found several solutions involving network issues. However this was working before ubuntu removed systemd from the ubuntu containers and I guess this must be connected to the systemd installation.

**Comment by eniocarboni** [comment]
Hi @janArb ,
 have you already tried with ?

`apt update && apt install -y dirmngr`

 then your gpg import:

`sudo /usr/bin/apt-key adv --no-tty --keyserver hkp://keyserver.ubuntu.com:80 --recv B1998361219BD9C9`

**Comment by janArb** [comment]
Hi @eniocarboni ,
I can't remember receiving a notification for your idea. I solved the issue at that time by creating my own systemd integration which was working successfully. However my integration is still not running under MacOS, which is why I always wanted to retry your integration in MacOS and try to solve the issue then. Sadly, I don't find time atm. I'll make a note and retry sometime in the future, because I will switch to MacOS eventually, too.
