### ISSUE TITLE
Is this still working

### ISSUE THREAD

**Issue by evans292** [eniocarboni/docker-ubuntu-systemd#6]
i wonder if this still working, because mine always exiting
<img width="1419" alt="image" src="https://github.com/user-attachments/assets/239c2d99-891d-4181-82d3-db3d4cd8630f">

**Comment by eniocarboni** [comment]
You can try using :rw instead of :ro in cgroup.
See #2

**Comment by evans292** [comment]
thank you for the response. but sadly mine still not working
<img width="1313" alt="image" src="https://github.com/user-attachments/assets/31783f72-b209-4f9e-ac84-6bdc3de65684">

**Comment by eniocarboni** [comment]
In my Ubuntu LTS 24.04 is all OK.

Try to add `--cgroupns=host` and then check the `docker logs <container id>`

**Comment by evans292** [comment]
thank you, i add `--cgroupns=host` and its working
